settings:
    music-disc-distance: 16 # The distance from which music discs can be heard in blocks.
    music-disc-volume: 1 # The master volume of music discs from 0-1. (You can set values like 0.5 for 50% volume).
    music-disc-max-download-size: 50 # Maximum download size in megabytes

translations:
    your-file-name: "Your file name is this: "